### ISSUE TITLE
MS Feedback: Please don't expose the paint-rect (viewportPaintRect)

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/PositionObserver#8]
#### Please don't expose the paint-rect (viewportPaintRect)

See also Issue #1

We are hoping for a much more robust definition and specification of the browser's viewport model (e.g., with regard to zooming) before exposing this data to web developers--it seems a bit premature to reveal it through this feature.
 
As far as implementation, we do have a PVR (paint-ahead bounding rect around the visible viewport) that we would not want to make observable or standardize because we view it as an implementation detail--we don't think those kinds of internal details should be the basis for signaling visibility because they would be difficult to get interoperable behavior.

**Comment by slightlyoff** [comment]
Sounds like there's relative consensus that this isn't appropriate for a V1, and perhaps not at all. Will remove.

Thanks for the feedback!
